export const mockDemand = [
  {
    country: "Paraguay",
    name: "Gov. Paraguay",
    type: "country",
    price: "2",
    quantity: "3 Millon",
    loi: "TRUE",
    added: "01/03/2021",
    "Estimated LOI": null,
    "Estimated import date": null,
    "Estimated Payment": null,
  },
  {
    country: "Philipines",
    name: "Gov. Philipines",
    type: "country",
    price: "1",
    quantity: "2 Millon",
    loi: "TRUE",
    added: "10/03/2021",
    "Estimated LOI": null,
    "Estimated import date": null,
    "Estimated Payment": null,
  },
  {
    country: "Brasil",
    name: "Estado do Maranion",
    type: "Gov State",
    price: "1",
    quantity: "5 Millon",
    loi: "TRUE",
    added: "10/03/2021",
    "Estimated LOI": null,
    "Estimated import date": null,
    "Estimated Payment": null,
  },
  {
    country: "Brasil",
    name: "Con. Maranion",
    type: "Gov. municipality",
    price: "1",
    quantity: "3 Millon",
    loi: "FALSE",
    added: "",
    "Estimated LOI": "15/03/2020",
    "Estimated import date": "25 Days delivery",
    "Estimated Payment": "Arrival",
  },
  {
    country: "Brasil",
    name: "LATAM Regional Consortio",
    type: "consortio",
    price: "1",
    quantity: "500 Millon",
    loi: "TRUE",
    added: "06/03/2021",
    "Estimated LOI": "",
    "Estimated import date": "18 Days delivery",
    "Estimated Payment": "Arrival",
  },
  {
    country: "Brasil",
    name: "Estado do para",
    type: "municipality",
    price: "1",
    quantity: "3 Millon",
    loi: "TRUE",
    added: "05/03/2021",
    "Estimated LOI": "",
    "Estimated import date": "19 Days delivery",
    "Estimated Payment": "Arrival",
  },
  {
    country: "Brasil",
    name: "Estado do Parana",
    type: "municipality",
    price: "1",
    quantity: "7Millon",
    loi: "TRUE",
    added: "10/03/2021",
    "Estimated LOI": "",
    "Estimated import date": "20 Days delivery",
    "Estimated Payment": "Arrival",
  },
  {
    country: "Brasil",
    name: "Consortio Centro Oeste",
    type: "municipality",
    price: "1",
    quantity: " 8 Millon",
    loi: "TRUE",
    added: "10/03/2021",
    "Estimated LOI": "",
    "Estimated import date": "21 Days delivery",
    "Estimated Payment": "Arrival",
  },
  {
    country: "Brasil",
    name: "Consortio Santa Catarian ",
    type: "municipality",
    price: "1",
    quantity: "2 Millon",
    loi: "TRUE",
    added: "07/03/2021",
    "Estimated LOI": "",
    "Estimated import date": "22 Days delivery",
    "Estimated Payment": "Arrival",
  },
  {
    country: "Brasil",
    name: "Consortio Sao Paolo",
    type: "municipality",
    price: "1",
    quantity: "10 Millon",
    loi: "TRUE",
    added: "10/03/2021",
    "Estimated LOI": "",
    "Estimated import date": "23 Days delivery",
    "Estimated Payment": "Arrival",
  },
  {
    country: "Brasil",
    name: "Consortio Sao Paolo",
    type: "Gov Monicipality",
    price: "1",
    quantity: "10 Millon",
    loi: "FALSE",
    added: "",
    "Estimated LOI": "17/03/2021",
    "Estimated import date": "25 Days delivery",
    "Estimated Payment": "Arrival",
  },
];
